"""Mixamo X Bot body renderer for Fork Simulator V5.

Loads models/x_bot.glb (generated by scripts/extract_fbx_mesh.py), converts
from Mixamo Y-up cm coords to scene Z-up metres, trims to upper body, and
drives the dominant arm toward the fork sensor each frame via 2-link IK.

Public API
----------
static_body_traces(mouth, dominant_hand, table_z) -> list[go.Mesh3d]
    Frame-independent body (torso+head+resting arm). Call from _static_traces.

arm_traces(mouth, dominant_hand, table_z, hand_xyz) -> list[go.Mesh3d]
    Per-frame posed dominant arm mesh. Call from build_figure.
"""

import functools
import numpy as np
import plotly.graph_objects as go
import trimesh

_GLB_PATH   = "models/x_bot.glb"
BODY_COLOR  = "#c06018"   # shirt-like orange
SKIN_COLOR  = "#e6b89c"   # skin


# ── Rotation: Mixamo Y-up → scene Z-up ──────────────────────────────────────
# Mixamo: X=right, Y=up, Z=backward (character faces -Z)
# Scene:  X=right, Z=up, Y=depth (patient faces -Y, toward camera)
# Mapping: scene_x=mix_x, scene_y=mix_z, scene_z=mix_y
_R_MIX2SCENE = np.array([[1, 0, 0],
                          [0, 0, 1],
                          [0, 1, 0]], dtype=float)


@functools.lru_cache(maxsize=1)
def _load_oriented():
    """Load X Bot, scale to metres, rotate to Z-up. Trim to upper body.
    Returns (verts, faces, anchors, groups) where verts are in scene
    orientation but NOT yet translated to the patient's mouth position.
    """
    mesh = trimesh.load(_GLB_PATH, force='mesh')
    v = (np.array(mesh.vertices, dtype=float)) / 100.0  # cm → metres
    f = np.array(mesh.faces, dtype=np.int32)

    # Rotate to Z-up
    v = (_R_MIX2SCENE @ v.T).T

    # Keep only upper body (above ~50% of height = roughly the waist)
    z_total  = v[:, 2].max() - v[:, 2].min()
    waist_z  = v[:, 2].min() + 0.50 * z_total
    keep     = v[:, 2] >= waist_z
    old2new  = np.full(len(v), -1, dtype=np.int32)
    old2new[keep] = np.arange(keep.sum())
    ub_v = v[keep].copy()
    rows = [(old2new[a], old2new[b], old2new[c])
            for a, b, c in f
            if old2new[a] >= 0 and old2new[b] >= 0 and old2new[c] >= 0]
    ub_f = np.array(rows, dtype=np.int32) if rows else np.zeros((0, 3), dtype=np.int32)

    # ── Geometric arm identification ────────────────────────────────────────
    z_max  = ub_v[:, 2].max()
    z_min  = ub_v[:, 2].min()
    z_span = z_max - z_min

    arm_lo = z_min + 0.40 * z_span
    arm_hi = z_min + 0.82 * z_span
    arm_zone = (ub_v[:, 2] >= arm_lo) & (ub_v[:, 2] <= arm_hi)
    r_arm_mask = arm_zone & (ub_v[:, 0] > 0.06)
    l_arm_mask = arm_zone & (ub_v[:, 0] < -0.06)

    def _shoulder(mask, side):
        if not mask.any():
            return np.array([0.3 if side == 'r' else -0.3, 0.0, z_min + 0.75 * z_span])
        pts = ub_v[mask]
        top = pts[pts[:, 2] > np.percentile(pts[:, 2], 80)]
        return top[np.argmin(top[:, 0])] if side == 'r' else top[np.argmax(top[:, 0])]

    r_sh = _shoulder(r_arm_mask, 'r')
    l_sh = _shoulder(l_arm_mask, 'l')

    def _hand_tip(mask, side):
        if not mask.any():
            return np.array([0.9 if side == 'r' else -0.9, 0.0, z_min + 0.75 * z_span])
        pts = ub_v[mask]
        return pts[np.argmax(pts[:, 0])] if side == 'r' else pts[np.argmin(pts[:, 0])]

    r_tip = _hand_tip(r_arm_mask, 'r')
    l_tip = _hand_tip(l_arm_mask, 'l')
    r_elb = (r_sh + r_tip) * 0.5
    l_elb = (l_sh + l_tip) * 0.5

    # Split each arm into upper (shoulder→elbow) and lower (elbow→tip) groups
    def _split_arm(mask, elbow_x, side):
        idx = np.where(mask)[0]
        ua = np.zeros(len(ub_v), bool)
        la = np.zeros(len(ub_v), bool)
        if len(idx) == 0:
            return ua, la
        xs = ub_v[idx, 0]
        ua[idx[(xs <= elbow_x) if side == 'r' else (xs >= elbow_x)]] = True
        la[idx[(xs >  elbow_x) if side == 'r' else (xs <  elbow_x)]] = True
        return ua, la

    r_ua, r_la = _split_arm(r_arm_mask, r_elb[0], 'r')
    l_ua, l_la = _split_arm(l_arm_mask, l_elb[0], 'l')

    # Approximate mouth position in oriented coords (front of face, mid-height of head)
    head_zone  = ub_v[:, 2] > z_min + 0.82 * z_span
    hpts = ub_v[head_zone] if head_zone.any() else ub_v
    mouth_ori  = np.array([0.0,
                           float(hpts[:, 1].min()) + 0.02,
                           float(hpts[:, 2].mean()) - 0.04])

    anchors = {
        "mouth_ori":  mouth_ori,
        "r_sh": r_sh, "r_elb": r_elb, "r_tip": r_tip,
        "r_upper_len": float(np.linalg.norm(r_elb - r_sh)),
        "r_fore_len":  float(np.linalg.norm(r_tip - r_elb)),
        "l_sh": l_sh, "l_elb": l_elb, "l_tip": l_tip,
        "l_upper_len": float(np.linalg.norm(l_elb - l_sh)),
        "l_fore_len":  float(np.linalg.norm(l_tip - l_elb)),
    }
    groups = {"r_ua": r_ua, "r_la": r_la, "l_ua": l_ua, "l_la": l_la}
    return ub_v, ub_f, anchors, groups


def _scene_offset(anchors, mouth_world):
    """Translation that aligns canonical mouth_ori to mouth_world."""
    return np.asarray(mouth_world, float) - anchors["mouth_ori"]


# ── Analytical 2-link IK ─────────────────────────────────────────────────────

def _rot_from_to(a, b):
    """3×3 rotation matrix rotating unit-vector a onto unit-vector b."""
    a = a / (np.linalg.norm(a) + 1e-9)
    b = b / (np.linalg.norm(b) + 1e-9)
    axis  = np.cross(a, b)
    s     = np.linalg.norm(axis)
    c     = float(np.dot(a, b))
    if s < 1e-9:
        return np.eye(3) if c > 0 else (np.eye(3) - 2 * np.outer(a, a))
    axis /= s
    K = np.array([[0, -axis[2], axis[1]],
                  [axis[2], 0, -axis[0]],
                  [-axis[1], axis[0], 0]])
    return np.eye(3) + s * K + (1 - c) * (K @ K)


def _solve_ik(shoulder, hand_target, upper_len, fore_len):
    """Law-of-cosines 2-link IK. Returns new_upper_dir and new_elbow_pos."""
    d_vec = hand_target - shoulder
    d     = float(np.linalg.norm(d_vec))
    d     = np.clip(d, 1e-6, upper_len + fore_len - 1e-4)
    d_hat = d_vec / d

    cos_a = np.clip(
        (upper_len ** 2 + d ** 2 - fore_len ** 2) / (2 * upper_len * d), -1, 1
    )
    alpha = np.arccos(cos_a)

    up   = np.array([0.0, 0.0, 1.0])
    side = np.cross(d_hat, up)
    if np.linalg.norm(side) < 1e-6:
        side = np.array([1.0, 0.0, 0.0])
    side /= np.linalg.norm(side)
    bend_axis = np.cross(side, d_hat)
    bend_axis /= np.linalg.norm(bend_axis) + 1e-9

    upper_dir   = np.cos(alpha) * d_hat + np.sin(alpha) * bend_axis
    elbow_world = shoulder + upper_len * upper_dir
    return upper_dir, elbow_world


# ── Pose + mesh assembly ─────────────────────────────────────────────────────

def _pose_full(verts_can, groups, anchors, dominant_hand, hand_target_world, offset):
    """Return vertex array with IK applied to the dominant arm."""
    v = verts_can.copy()
    side = 'r' if dominant_hand == 'Right' else 'l'

    sh  = anchors[f'{side}_sh']
    elb = anchors[f'{side}_elb']
    tip = anchors[f'{side}_tip']
    u_l = anchors[f'{side}_upper_len']
    f_l = anchors[f'{side}_fore_len']

    rest_upper_dir = (elb - sh)  / (np.linalg.norm(elb - sh)  + 1e-9)
    rest_fore_dir  = (tip - elb) / (np.linalg.norm(tip - elb) + 1e-9)

    # Convert hand target from world (with translation) to oriented canonical
    hand_can = hand_target_world - offset

    new_upper_dir, new_elbow = _solve_ik(sh, hand_can, u_l, f_l)
    new_fore_dir = (hand_can - new_elbow) / (np.linalg.norm(hand_can - new_elbow) + 1e-9)

    R_upper = _rot_from_to(rest_upper_dir, new_upper_dir)
    R_fore  = _rot_from_to(rest_fore_dir,  new_fore_dir)

    ua_mask = groups[f'{side}_ua']
    la_mask = groups[f'{side}_la']

    if ua_mask.any():
        pts = v[ua_mask] - sh
        v[ua_mask] = (R_upper @ pts.T).T + sh

    if la_mask.any():
        pts = v[la_mask] - sh
        pts = (R_upper @ pts.T).T + sh   # co-rotate with upper arm first
        pts = pts - new_elbow            # then rotate forearm around new elbow
        v[la_mask] = (R_fore @ pts.T).T + new_elbow

    return v


def _mesh3d(v, f, color, opacity, name):
    return go.Mesh3d(
        x=v[:, 0].tolist(), y=v[:, 1].tolist(), z=v[:, 2].tolist(),
        i=f[:, 0].tolist(), j=f[:, 1].tolist(), k=f[:, 2].tolist(),
        color=color, opacity=opacity, flatshading=False,
        name=name, showlegend=bool(name and not name.startswith('_')),
    )


# ── Public API ───────────────────────────────────────────────────────────────

@functools.lru_cache(maxsize=32)
def static_body_traces(mouth, dominant_hand, table_z):
    """Frame-independent body: torso + head. Call from _static_traces."""
    verts_can, faces, anchors, groups = _load_oriented()
    mouth = np.asarray(mouth, float)
    offset = _scene_offset(anchors, mouth)

    # Mask out dominant arm for static trace (it will be drawn per-frame)
    side = 'r' if dominant_hand == 'Right' else 'l'
    arm_mask = groups[f'{side}_ua'] | groups[f'{side}_la']
    keep = ~arm_mask
    old2new = np.full(len(verts_can), -1, dtype=np.int32)
    old2new[keep] = np.arange(keep.sum())
    v_static = verts_can[keep] + offset
    rows = [(old2new[a], old2new[b], old2new[c])
            for a, b, c in faces
            if old2new[a] >= 0 and old2new[b] >= 0 and old2new[c] >= 0]
    f_static = np.array(rows, dtype=np.int32) if rows else np.zeros((0, 3), dtype=np.int32)

    if len(f_static) == 0:
        return []
    return [_mesh3d(v_static, f_static, BODY_COLOR, 0.85, "Body")]


def arm_traces(mouth, dominant_hand, table_z, hand_xyz):
    """Per-frame dominant arm mesh with IK applied."""
    verts_can, faces, anchors, groups = _load_oriented()
    mouth    = np.asarray(mouth,    float)
    hand_xyz = np.asarray(hand_xyz, float)
    offset   = _scene_offset(anchors, mouth)

    side     = 'r' if dominant_hand == 'Right' else 'l'
    arm_mask = groups[f'{side}_ua'] | groups[f'{side}_la']

    posed_verts = _pose_full(verts_can, groups, anchors, dominant_hand, hand_xyz, offset)
    posed_verts += offset

    arm_v   = posed_verts[arm_mask]
    old2new = np.full(len(verts_can), -1, dtype=np.int32)
    old2new[np.where(arm_mask)[0]] = np.arange(arm_mask.sum())
    rows = [(old2new[a], old2new[b], old2new[c])
            for a, b, c in faces
            if old2new[a] >= 0 and old2new[b] >= 0 and old2new[c] >= 0]
    arm_f = np.array(rows, dtype=np.int32) if rows else np.zeros((0, 3), dtype=np.int32)

    if len(arm_f) == 0:
        return []
    return [_mesh3d(arm_v, arm_f, SKIN_COLOR, 0.85, "_arm")]


# ── Self-test ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    verts_can, faces, anchors, groups = _load_oriented()
    print("Verts:", verts_can.shape, "Faces:", faces.shape)
    print("Mouth oriented:", anchors["mouth_ori"])
    print("R shoulder:", anchors["r_sh"])
    print("R elbow:   ", anchors["r_elb"])
    print("R hand tip:", anchors["r_tip"])
    print("Upper len:", anchors["r_upper_len"], "  Fore len:", anchors["r_fore_len"])

    sh = anchors["r_sh"]
    u  = anchors["r_upper_len"]
    f  = anchors["r_fore_len"]

    # Hand at shoulder → elbow should clamp to full extension
    dir_u, elb = _solve_ik(sh, sh + np.array([0.001, 0, 0]), u, f)
    print("IK at shoulder (near-zero dist) — upper_dir:", dir_u.round(3))

    # Hand at full extension along +X
    target_ext = sh + np.array([u + f - 0.001, 0, 0])
    dir_u2, elb2 = _solve_ik(sh, target_ext, u, f)
    assert abs(dir_u2[0] - 1.0) < 0.05, f"Expected X-aligned at extension, got {dir_u2}"
    print("IK at full extension — upper_dir:", dir_u2.round(3), "PASS")

    # Mouth = (0, 0, 0.3) scene → offset should shift body accordingly
    test_mouth = np.array([0.0, 0.0, 0.3])
    offset = _scene_offset(anchors, test_mouth)
    print("Scene offset for mouth=(0,0,0.3):", offset.round(3))
    print("All self-tests passed.")
